require("dotenv").config();

const qrcode = require("qrcode-terminal");
const { Client, LocalAuth } = require("whatsapp-web.js");
const {
  logMessage,
  insertOrUpdateIssue,
  getAllIssues,
  getNewIssues,
  getConversation,
  resolveConversation
} = require("./db");
const { extractIssue } = require("./extractor");
const { handleCommand } = require("./commands");
const { advanceConversation } = require("./conversationManager");

const groupName = process.env.GROUP_NAME;
const botName = process.env.BOT_NAME;
const hrMemberNumbers = (process.env.HR_MEMBER_NUMBERS || "")
  .split(",")
  .map((item) => item.replace(/\D/g, "").trim())
  .filter(Boolean);
const hrMemberSet = new Set(hrMemberNumbers);

if (!groupName || !botName) {
  console.error("Missing required env variables: GROUP_NAME and/or BOT_NAME");
  process.exit(1);
}

function formatDate(value) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "N/A";
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = date.getFullYear();
  return `${day}/${month}/${year}`;
}

function buildTestSummaryReport() {
  const allIssues = getAllIssues();
  const newIssuesToday = getNewIssues(1).filter((item) => {
    const firstSeen = new Date(item.first_seen);
    const now = new Date();
    return (
      !Number.isNaN(firstSeen.getTime()) &&
      firstSeen.getDate() === now.getDate() &&
      firstSeen.getMonth() === now.getMonth() &&
      firstSeen.getFullYear() === now.getFullYear()
    );
  });

  const topIssues = [...allIssues]
    .filter((item) => Number(item.frequency || 1) >= 2)
    .sort((a, b) => Number(b.frequency || 1) - Number(a.frequency || 1))
    .slice(0, 5);

  const topIssuesText =
    topIssues.length > 0
      ? topIssues.map((item) => `- [${item.category}] ${item.issue_summary} (seen ${item.frequency} times)`).join("\n")
      : "No repeated issues yet.";

  return `Daily HR Issues Report - ${formatDate(new Date())}

Total issues tracked: ${allIssues.length}
New issues today: ${newIssuesToday.length}
Resolved today: 0

Top repeated issues:
${topIssuesText}

Generated by HR Bot`;
}

const client = new Client({
  authStrategy: new LocalAuth(),
  puppeteer: {
    headless: true
  }
});

client.on("qr", (qr) => {
  console.log("Scan this QR code with WhatsApp:");
  qrcode.generate(qr, { small: true });
});

client.on("ready", () => {
  console.log("Bot is ready");
  console.log(`Monitoring group name from .env: "${groupName}"`);
  console.log(`Bot command trigger from .env: "@${botName}"`);
});

client.on("message", async (message) => {
  try {
    const chat = await message.getChat();
    let senderContact = null;

    let sender = "Unknown";
    try {
      const contact = await message.getContact();
      senderContact = contact;
      sender = contact.pushname || contact.name || contact.number || message.from;
    } catch (contactError) {
      sender = message.from || "Unknown";
    }

    const chatName = chat.name || "(No chat name)";
    const text = message.body || "";
    const senderId = message.author || message.from || "";
    const senderNumberFromContact = (senderContact?.number || "").toString().replace(/\D/g, "");
    const senderNumberFromId = senderId.split("@")[0].replace(/\D/g, "");
    const senderNumber = senderNumberFromContact || senderNumberFromId;

    const isMonitoredGroup = chat.isGroup && chatName === groupName;
    if (!isMonitoredGroup) return;
    if (message.fromMe) return;

    console.log(`[MONITORED GROUP] ${chatName} | From: ${sender} | Message: ${text}`);

    const mentionToken = `@${botName}`.toLowerCase();
    const lowerText = text.toLowerCase();
    const hasBotMention = lowerText.includes(mentionToken);
    const isHrMember = hrMemberSet.has(senderNumber);

    if (hasBotMention) {
      const mentionRegex = new RegExp(`@${botName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`, "ig");
      const strippedCommand = text.replace(mentionRegex, "").trim();
      const normalizedCommand = strippedCommand.toLowerCase();

      if (normalizedCommand === "test summary") {
        try {
          await message.reply(buildTestSummaryReport());
        } catch (summaryError) {
          console.error("Failed to send test summary:", summaryError.message);
          await message.reply("Unable to send summary right now.");
        }

        logMessage({
          message: text,
          timestamp: new Date().toISOString(),
          sender,
          issue_detected: 0
        });
        return;
      }

      const commandReply = handleCommand(strippedCommand, client, message);
      if (commandReply) {
        await message.reply(commandReply);
        logMessage({
          message: text,
          timestamp: new Date().toISOString(),
          sender,
          issue_detected: 0
        });
        return;
      }

      if (senderId) {
        const activeConversation = getConversation(senderId);
        if (activeConversation) {
          resolveConversation(senderId);
        }
        const conversationInput = strippedCommand || text;
        await advanceConversation(senderId, conversationInput, client, chat.id?._serialized);
      }
    } else if (senderId) {
      const activeConversation = getConversation(senderId);
      if (activeConversation) {
        await advanceConversation(senderId, text, client, chat.id?._serialized);
      }
    }

    const extracted = await extractIssue(text);
    if (extracted.is_issue) {
      insertOrUpdateIssue({
        raw_message: text,
        category: extracted.category || "Other",
        issue_summary: extracted.issue_summary || "Unspecified issue",
        candidate_name: extracted.candidate_name || null,
        resolution_hint: extracted.resolution_hint || null,
        first_seen: new Date().toISOString(),
        last_seen: new Date().toISOString()
      });
    }

    logMessage({
      message: text,
      timestamp: new Date().toISOString(),
      sender,
      issue_detected: extracted.is_issue ? 1 : 0
    });
  } catch (error) {
    console.error("Failed to process incoming message:", error.message);
  }
});

client.on("auth_failure", (msg) => {
  console.error("Authentication failed:", msg);
});

client.on("disconnected", (reason) => {
  console.error("Client disconnected:", reason);
});

client.initialize();
